// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: MergeESCTaskCodes
//     Last Modified On: 6/28/2023 8:50:22 AM
//     Written By: Kirk Barrett
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SQLPLUS.Build.Test.Basic.Sync.Models
{
    #region usings

    using SQLPLUS.Build.Test.Basic.UserDefinedTypes;
    using SqlPlusBase;
    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Input object for the MergeESCTaskCodes service.
    /// </summary>
    public partial class MergeESCTaskCodesInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for MergeESCTaskCodesInput.
        /// </summary>
        public MergeESCTaskCodesInput() { }

        /// <summary>
        /// Parameterized constructor for MergeESCTaskCodesInput.
        /// </summary>
        /// <param name="Data">Maps to parameter @Data.</param>
        public MergeESCTaskCodesInput(List<ETask> Data)
        {
            this.Data = Data;
        }

        #endregion Constructors

        #region Fields

        private List<ETask> _Data;
        /// <summary>
        /// Maps to parameter @Data.
        /// </summary>
        public List<ETask> Data
        {
            get => _Data;
            set => _Data = value;
        }

        #endregion

    }
}