// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SQLPLUS.Builder.Render.T4Net
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using SQLPLUS.Builder;
    using SQLPLUS.Builder.ConfigurationModels;
    using SQLPLUS.Builder.TemplateModels;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class InputObject : InputObjectBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
");
            
            #line 16 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
if (routine.RoutineType == "QUERY"){
            
            #line default
            #line hidden
            this.Write("//     Underlying Query: ");
            
            #line 17 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 18 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
}else{
            
            #line default
            #line hidden
            this.Write("//     Underlying Routine: ");
            
            #line 19 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 20 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
}
            
            #line default
            #line hidden
            this.Write("//     Last Modified On: ");
            
            #line 21 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.LastModified.ToString()));
            
            #line default
            #line hidden
            this.Write("\r\n//     Written By: ");
            
            #line 22 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Author));
            
            #line default
            #line hidden
            this.Write("\r\n// </auto-generated>\r\n// ------------------------------------------------------" +
                    "--------------------------------------------------\r\nnamespace ");
            
            #line 25 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.ModelNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 27 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
if (routine.UseNullableReferenceTypes){
            
            #line default
            #line hidden
            this.Write("    #nullable enable\r\n\r\n");
            
            #line 30 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
}
            
            #line default
            #line hidden
            this.Write("    #region usings\r\n\r\n");
            
            #line 33 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
foreach(string @using in routine.InputUsings){
            
            #line default
            #line hidden
            this.Write("    using ");
            
            #line 34 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(@using));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 35 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n    #endregion usings\r\n\r\n    /// <summary>\r\n    /// Input object for the ");
            
            #line 40 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write(" service.\r\n    /// </summary>\r\n    public partial class ");
            
            #line 42 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.InputObjectName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 42 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.InputImplements));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        #region Constructors\r\n\r\n        /// <summary>\r\n        /// Empty" +
                    " constructor for ");
            
            #line 47 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.InputObjectName));
            
            #line default
            #line hidden
            this.Write(".\r\n        /// </summary>\r\n        public ");
            
            #line 49 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.InputObjectName));
            
            #line default
            #line hidden
            this.Write("() { }\r\n");
            
            #line 50 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
if (routine.InputParameters.Count != 0){
            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>\r\n        /// Parameterized constructor for ");
            
            #line 53 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.InputObjectName));
            
            #line default
            #line hidden
            this.Write(".\r\n        /// </summary>\r\n");
            
            #line 55 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
  foreach (Parameter p in routine.InputParameters){
            
            #line default
            #line hidden
            this.Write("        /// <param name=\"");
            
            #line 56 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 56 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.Comment));
            
            #line default
            #line hidden
            this.Write("</param>\r\n");
            
            #line 57 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
  }
            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 58 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.InputObjectName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 58 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.InputParametersConcat));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n");
            
            #line 60 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
  foreach (Parameter p in routine.InputParameters){
            
            #line default
            #line hidden
            this.Write("            this.");
            
            #line 61 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 61 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 62 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
  }
            
            #line default
            #line hidden
            this.Write("        }\r\n");
            
            #line 64 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n        #endregion Constructors\r\n\r\n        #region Fields\r\n\r\n");
            
            #line 70 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
foreach(Parameter p in routine.InputParameters){
            
            #line default
            #line hidden
            this.Write("        private ");
            
            #line 71 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyType));
            
            #line default
            #line hidden
            this.Write(" _");
            
            #line 71 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            
            #line 71 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.DefaultValue == null ? "" : " = " + p.DefaultValue));
            
            #line default
            #line hidden
            this.Write(";\r\n        /// <summary>\r\n        /// ");
            
            #line 73 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.Comment));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n");
            
            #line 75 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
  foreach(string annotation in p.Annotations){
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 76 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(annotation));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 77 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
  }
            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 78 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 78 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get => _");
            
            #line 80 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 81 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
  if (p.IsTableValueParameter || (!build.BuildOptions.ImplementIChangeTracking && !build.BuildOptions.ImplementIRevertibleChangeTracking && !build.BuildOptions.ImplementINotifyPropertyChanged)){
            
            #line default
            #line hidden
            this.Write("            set => _");
            
            #line 82 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n");
            
            #line 83 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
  }else{
            
            #line default
            #line hidden
            this.Write("            set\r\n            {\r\n                ");
            
            #line 86 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.EqualityTestFormatter));
            
            #line default
            #line hidden
            this.Write("\r\n                {\r\n");
            
            #line 88 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
    if(build.BuildOptions.ImplementIRevertibleChangeTracking){
            
            #line default
            #line hidden
            this.Write("                    _ChangedProperties[\"");
            
            #line 89 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write("\"] = _");
            
            #line 89 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 90 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
    }
            
            #line default
            #line hidden
            this.Write("                    _");
            
            #line 91 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n                    HandlePropertyChanged(nameof(");
            
            #line 92 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write("));\r\n                }\r\n            }\r\n");
            
            #line 95 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
  }
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n");
            
            #line 98 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
}
            
            #line default
            #line hidden
            this.Write("        #endregion\r\n\r\n");
            
            #line 101 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
if(build.BuildOptions.ImplementIChangeTracking || build.BuildOptions.ImplementIRevertibleChangeTracking  || build.BuildOptions.ImplementINotifyPropertyChanged){
            
            #line default
            #line hidden
            this.Write("        #region Property Changed Management\r\n\r\n");
            
            #line 104 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
}
            
            #line default
            #line hidden
            
            #line 105 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
if(build.BuildOptions.ImplementIRevertibleChangeTracking){
            
            #line default
            #line hidden
            this.Write("        private Dictionary<string,object> _ChangedProperties = new Dictionary<str" +
                    "ing,object>();\r\n");
            
            #line 107 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
}
            
            #line default
            #line hidden
            
            #line 108 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
if(build.BuildOptions.ImplementINotifyPropertyChanged){
            
            #line default
            #line hidden
            this.Write("        public event PropertyChangedEventHandler PropertyChanged;\r\n");
            
            #line 110 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
}
            
            #line default
            #line hidden
            
            #line 111 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
if(build.BuildOptions.ImplementIChangeTracking || build.BuildOptions.ImplementIRevertibleChangeTracking || build.BuildOptions.ImplementINotifyPropertyChanged){
            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>\r\n        /// Property change handler.\r\n        /// </summ" +
                    "ary>\r\n        private void HandlePropertyChanged(string propertyName)\r\n        {" +
                    "\r\n");
            
            #line 118 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
  if(build.BuildOptions.ImplementIChangeTracking || build.BuildOptions.ImplementIRevertibleChangeTracking){
            
            #line default
            #line hidden
            this.Write("            IsChanged = true;\r\n");
            
            #line 120 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
  }
            
            #line default
            #line hidden
            
            #line 121 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
  if(build.BuildOptions.ImplementINotifyPropertyChanged){
            
            #line default
            #line hidden
            this.Write("            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyNa" +
                    "me));\r\n");
            
            #line 123 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
  }
            
            #line default
            #line hidden
            this.Write("        }\r\n");
            
            #line 125 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
}
            
            #line default
            #line hidden
            
            #line 126 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
if(build.BuildOptions.ImplementIChangeTracking || build.BuildOptions.ImplementIRevertibleChangeTracking){
            
            #line default
            #line hidden
            this.Write("        /// <summary>\r\n        /// Gets the object\'s changed status.\r\n        ///" +
                    " </summary>\r\n        public bool IsChanged { private set; get; }\r\n");
            
            #line 131 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
}
            
            #line default
            #line hidden
            
            #line 132 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
if(build.BuildOptions.ImplementIChangeTracking || build.BuildOptions.ImplementIRevertibleChangeTracking){
            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>\r\n        /// Resets the object\'s state to unchanged by ac" +
                    "cepting the modifications.\r\n        /// </summary>\r\n        public void AcceptCh" +
                    "anges()\r\n        {\r\n");
            
            #line 139 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
  if(build.BuildOptions.ImplementIRevertibleChangeTracking){
            
            #line default
            #line hidden
            this.Write("            _ChangedProperties.Clear();\r\n");
            
            #line 141 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
  }
            
            #line default
            #line hidden
            this.Write("            IsChanged = false;\r\n        }\r\n");
            
            #line 144 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
}
            
            #line default
            #line hidden
            
            #line 145 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
if(build.BuildOptions.ImplementIRevertibleChangeTracking){
            
            #line default
            #line hidden
            this.Write(@"
        /// <summary>
        /// Resets the object's state to unchanged by rejecting the modifications.
        /// </summary>
        public void RejectChanges()
        {
            foreach (string key in _ChangedProperties.Keys)
            {
                switch (key)
                {
");
            
            #line 156 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
  foreach(Parameter p in routine.InputParameters){
            
            #line default
            #line hidden
            this.Write("                    case nameof(");
            
            #line 157 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write("):\r\n                        _");
            
            #line 158 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write(" = (");
            
            #line 158 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyType));
            
            #line default
            #line hidden
            this.Write(")_ChangedProperties[\"");
            
            #line 158 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write("\"];\r\n                        break;\r\n");
            
            #line 160 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
  }
            
            #line default
            #line hidden
            this.Write("                }\r\n            }\r\n\r\n            _ChangedProperties.Clear();\r\n    " +
                    "        IsChanged = false;\r\n        }\r\n");
            
            #line 167 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
}
            
            #line default
            #line hidden
            
            #line 168 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
if(build.BuildOptions.ImplementIChangeTracking || build.BuildOptions.ImplementIRevertibleChangeTracking || build.BuildOptions.ImplementINotifyPropertyChanged){
            
            #line default
            #line hidden
            this.Write("\r\n        #endregion Property Changed Management\r\n");
            
            #line 171 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"
}
            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\InputObject.tt"

private global::SQLPLUS.Builder.TemplateModels.Routine _routineField;

/// <summary>
/// Access the routine parameter of the template.
/// </summary>
private global::SQLPLUS.Builder.TemplateModels.Routine routine
{
    get
    {
        return this._routineField;
    }
}

private global::SQLPLUS.Builder.ConfigurationModels.ProjectInformation _projectField;

/// <summary>
/// Access the project parameter of the template.
/// </summary>
private global::SQLPLUS.Builder.ConfigurationModels.ProjectInformation project
{
    get
    {
        return this._projectField;
    }
}

private global::SQLPLUS.Builder.ConfigurationModels.BuildDefinition _buildField;

/// <summary>
/// Access the build parameter of the template.
/// </summary>
private global::SQLPLUS.Builder.ConfigurationModels.BuildDefinition build
{
    get
    {
        return this._buildField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool routineValueAcquired = false;
if (this.Session.ContainsKey("routine"))
{
    this._routineField = ((global::SQLPLUS.Builder.TemplateModels.Routine)(this.Session["routine"]));
    routineValueAcquired = true;
}
if ((routineValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("routine");
    if ((data != null))
    {
        this._routineField = ((global::SQLPLUS.Builder.TemplateModels.Routine)(data));
    }
}
bool projectValueAcquired = false;
if (this.Session.ContainsKey("project"))
{
    this._projectField = ((global::SQLPLUS.Builder.ConfigurationModels.ProjectInformation)(this.Session["project"]));
    projectValueAcquired = true;
}
if ((projectValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("project");
    if ((data != null))
    {
        this._projectField = ((global::SQLPLUS.Builder.ConfigurationModels.ProjectInformation)(data));
    }
}
bool buildValueAcquired = false;
if (this.Session.ContainsKey("build"))
{
    this._buildField = ((global::SQLPLUS.Builder.ConfigurationModels.BuildDefinition)(this.Session["build"]));
    buildValueAcquired = true;
}
if ((buildValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("build");
    if ((data != null))
    {
        this._buildField = ((global::SQLPLUS.Builder.ConfigurationModels.BuildDefinition)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class InputObjectBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
