// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SQLPLUS.Builder.Render.T4Net
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using SQLPLUS.Builder;
    using SQLPLUS.Builder.ConfigurationModels;
    using SQLPLUS.Builder.TemplateModels;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ServiceMethod : ServiceMethodBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
");
            
            #line 16 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
if (routine.RoutineType == "QUERY"){
            
            #line default
            #line hidden
            this.Write("//     Underlying Query: ");
            
            #line 17 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 18 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
}else{
            
            #line default
            #line hidden
            this.Write("//     Underlying Routine: ");
            
            #line 19 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 20 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
}
            
            #line default
            #line hidden
            this.Write("//     Last Modified On: ");
            
            #line 21 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.LastModified.ToString()));
            
            #line default
            #line hidden
            this.Write("\r\n//     Written By: ");
            
            #line 22 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Author));
            
            #line default
            #line hidden
            this.Write("\r\n// </auto-generated>\r\n// ------------------------------------------------------" +
                    "--------------------------------------------------\r\nnamespace ");
            
            #line 25 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.ServiceNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 27 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
if (routine.UseNullableReferenceTypes){
            
            #line default
            #line hidden
            this.Write("    #nullable enable\r\n\r\n");
            
            #line 30 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
}
            
            #line default
            #line hidden
            this.Write("    #region Using Statments\r\n\r\n");
            
            #line 33 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
foreach(string @using in routine.ServiceUsings){
            
            #line default
            #line hidden
            this.Write("    using ");
            
            #line 34 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(@using));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 35 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n    #endregion Using Statements\r\n\r\n    /// <summary>\r\n    /// This file contain" +
                    "s the source code for the ");
            
            #line 40 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write(" routine.\r\n    /// </summary>\r\n    public partial class Service\r\n    {\r\n        #" +
                    "region Build SqlCommand\r\n\r\n        private SqlCommand ");
            
            #line 46 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.BuildCommandName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 46 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.BuildCommandParameters));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            SqlCommand result = new SqlCommand()\r\n            {\r\n");
            
            #line 50 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
if(routine.CommandTimeout.HasValue){
            
            #line default
            #line hidden
            this.Write("                CommandTimeout = ");
            
            #line 51 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.CommandTimeout.Value));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 52 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
}
            
            #line default
            #line hidden
            this.Write("                CommandType = ");
            
            #line 53 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.AdoCommandType));
            
            #line default
            #line hidden
            this.Write(",\r\n                CommandText = ");
            
            #line 54 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.AdoCommandText));
            
            #line default
            #line hidden
            this.Write(",\r\n                Connection = cnn\r\n            };\r\n");
            
            #line 57 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
foreach(Parameter p in routine.Parameters){
            
            #line default
            #line hidden
            this.Write("\r\n            result.Parameters.Add(new SqlParameter()\r\n            {\r\n          " +
                    "      ParameterName = \"");
            
            #line 61 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.AdoParameterName));
            
            #line default
            #line hidden
            this.Write("\",\r\n                Direction = ");
            
            #line 62 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.AdoDirection));
            
            #line default
            #line hidden
            this.Write(",\r\n                SqlDbType = ");
            
            #line 63 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.AdoSqlDbType));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 64 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  if(p.AdoSize != null){
            
            #line default
            #line hidden
            this.Write("                Size = ");
            
            #line 65 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.AdoSize ?? p.AdoSize));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 66 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  }
            
            #line default
            #line hidden
            
            #line 67 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  if(p.AdoScale != null){
            
            #line default
            #line hidden
            this.Write("                Scale = ");
            
            #line 68 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.AdoScale));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 69 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  }
            
            #line default
            #line hidden
            
            #line 70 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  if(p.AdoPrecision != null){
            
            #line default
            #line hidden
            this.Write("                Precision = ");
            
            #line 71 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.AdoPrecision));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 72 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  }
            
            #line default
            #line hidden
            
            #line 73 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  if(p.UserDefinedTypeSchema != null){
            
            #line default
            #line hidden
            this.Write("                TypeName = \"");
            
            #line 74 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.UserDefinedTypeSchema));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 74 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.UserDefinedTypeName));
            
            #line default
            #line hidden
            this.Write("\",\r\n");
            
            #line 75 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  }
            
            #line default
            #line hidden
            
            #line 76 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  if(p.AdoUdtTypeName != null){
            
            #line default
            #line hidden
            this.Write("                UdtTypeName = \"");
            
            #line 77 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.AdoUdtTypeName));
            
            #line default
            #line hidden
            this.Write("\",\r\n");
            
            #line 78 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  }
            
            #line default
            #line hidden
            
            #line 79 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  if(p.IsRequired){
            
            #line default
            #line hidden
            
            #line 80 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
    if(p.UserDefinedTypeSchema != null){
            
            #line default
            #line hidden
            this.Write("\t\t\t    Value = Helpers.BuildDataTable(input.");
            
            #line 81 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 82 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
    }else{
            
            #line default
            #line hidden
            this.Write("                Value = input.");
            
            #line 83 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 84 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
    }
            
            #line default
            #line hidden
            
            #line 85 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  }else{
            
            #line default
            #line hidden
            this.Write("                Value = DBNull.Value\r\n");
            
            #line 87 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  }
            
            #line default
            #line hidden
            this.Write("            });\r\n");
            
            #line 89 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 91 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
foreach(Parameter p in routine.InputParameters){
            
            #line default
            #line hidden
            
            #line 92 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  if (!p.IsRequired){
            
            #line default
            #line hidden
            this.Write("            if (input.");
            
            #line 93 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n            {\r\n");
            
            #line 95 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
    if(p.UserDefinedTypeSchema != null){
            
            #line default
            #line hidden
            this.Write("\t\t\t    result.Parameters[\"");
            
            #line 96 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.Name));
            
            #line default
            #line hidden
            this.Write("\"].Value = Helpers.BuildDataTable(input.");
            
            #line 96 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 97 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
    }else{
            
            #line default
            #line hidden
            this.Write("                result.Parameters[\"");
            
            #line 98 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.Name));
            
            #line default
            #line hidden
            this.Write("\"].Value = input.");
            
            #line 98 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 99 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
    }
            
            #line default
            #line hidden
            this.Write("            }\r\n");
            
            #line 101 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  }
            
            #line default
            #line hidden
            
            #line 102 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
}
            
            #line default
            #line hidden
            this.Write("            return result;\r\n        }\r\n\r\n        #endregion Build SqlCommand\r\n");
            
            #line 107 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
if (routine.NonInputParameters.Count != 0){
            
            #line default
            #line hidden
            this.Write("\r\n        #region Read Output Parameters And Return Value\r\n\r\n        private void" +
                    " ");
            
            #line 111 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.SetParametersName));
            
            #line default
            #line hidden
            this.Write("(SqlCommand cmd, ");
            
            #line 111 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("Output output)\r\n        {\r\n");
            
            #line 113 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
foreach(Parameter p in routine.NonInputParameters){
            
            #line default
            #line hidden
            this.Write("            if(cmd.Parameters[");
            
            #line 114 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.Index));
            
            #line default
            #line hidden
            this.Write("].Value != DBNull.Value)\r\n            {\r\n                output.");
            
            #line 116 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.PropertyName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 116 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(OutParameterCast(p)));
            
            #line default
            #line hidden
            this.Write("cmd.Parameters[");
            
            #line 116 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.Index));
            
            #line default
            #line hidden
            this.Write("].Value;\r\n            }\r\n");
            
            #line 118 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
}
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        #endregion Read Output Parameters And Return Value\r\n");
            
            #line 122 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
}
            
            #line default
            #line hidden
            
            #line 123 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
if(routine.SelectType != SelectTypes.NonQuery){
            
            #line default
            #line hidden
            this.Write("\r\n        #region Reader To Result Objects\r\n");
            
            #line 126 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
}
            
            #line default
            #line hidden
            
            #line 127 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
if(routine.SelectType == SelectTypes.SingleRow || routine.SelectType == SelectTypes.MultiRow){
            
            #line default
            #line hidden
            this.Write("        \r\n        private ");
            
            #line 129 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("Result ");
            
            #line 129 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("_ResultData(SqlDataReader rdr)\r\n        {\r\n            return new ");
            
            #line 131 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("Result(\r\n");
            
            #line 132 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  foreach(Column c in routine.ResultSets[0].Columns){
            
            #line default
            #line hidden
            
            #line 133 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      if(c.IsNullable){
            
            #line default
            #line hidden
            this.Write("            rdr.IsDBNull(");
            
            #line 134 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(c.Index));
            
            #line default
            #line hidden
            this.Write(") ? null : ");
            
            #line 134 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Format(c.AdoGetterFormatter,c.Index)));
            
            #line default
            #line hidden
            
            #line 134 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CommaIfNotLast(routine.ResultSets[0].Columns, c)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 135 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      }else{
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 136 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Format(c.AdoGetterFormatter,c.Index)));
            
            #line default
            #line hidden
            
            #line 136 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CommaIfNotLast(routine.ResultSets[0].Columns, c)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 137 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      }
            
            #line default
            #line hidden
            
            #line 138 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  }
            
            #line default
            #line hidden
            this.Write("            );\r\n        }\r\n");
            
            #line 141 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
}
            
            #line default
            #line hidden
            
            #line 142 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
if(routine.SelectType == SelectTypes.MultiSet){
            
            #line default
            #line hidden
            
            #line 143 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  foreach(ResultSet rs in routine.ResultSets){
            
            #line default
            #line hidden
            
            #line 144 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      if(rs.SelectType == SelectTypes.SingleRow || rs.SelectType == SelectTypes.MultiRow){
            
            #line default
            #line hidden
            this.Write("      \r\n        private ");
            
            #line 146 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("Result.");
            
            #line 146 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rs.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 146 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 146 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rs.Name));
            
            #line default
            #line hidden
            this.Write("(SqlDataReader rdr)\r\n        {\r\n            return new ");
            
            #line 148 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("Result.");
            
            #line 148 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rs.Name));
            
            #line default
            #line hidden
            this.Write("(\r\n");
            
            #line 149 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  foreach (Column c in rs.Columns){
            
            #line default
            #line hidden
            
            #line 150 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      if(c.IsNullable){
            
            #line default
            #line hidden
            this.Write("                rdr.IsDBNull(");
            
            #line 151 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(c.Index));
            
            #line default
            #line hidden
            this.Write(") ? null : ");
            
            #line 151 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Format(c.AdoGetterFormatter,c.Index)));
            
            #line default
            #line hidden
            
            #line 151 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CommaIfNotLast(rs.Columns, c)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 152 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      }else{
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 153 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Format(c.AdoGetterFormatter,c.Index)));
            
            #line default
            #line hidden
            
            #line 153 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CommaIfNotLast(rs.Columns, c)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 154 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      }
            
            #line default
            #line hidden
            
            #line 155 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  }
            
            #line default
            #line hidden
            this.Write("            );\r\n        }\r\n");
            
            #line 158 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      }
            
            #line default
            #line hidden
            
            #line 159 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  }
            
            #line default
            #line hidden
            
            #line 160 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
}
            
            #line default
            #line hidden
            
            #line 161 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
if(routine.SelectType != SelectTypes.NonQuery){
            
            #line default
            #line hidden
            this.Write("    \r\n        #endregion Reader To Result Objects\r\n");
            
            #line 163 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
}
            
            #line default
            #line hidden
            
            #line 164 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
if(routine.SelectType == SelectTypes.MultiSet){
            
            #line default
            #line hidden
            this.Write("\r\n        #region MultiSetResolve\r\n\r\n        private string ");
            
            #line 168 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.ServiceName));
            
            #line default
            #line hidden
            this.Write(@"_Resolve(SqlDataReader rdr)
        {
            string[] array = new string[rdr.FieldCount];
            for (int idx = 0; idx != array.Length; idx++)
            {
                array[idx] = rdr.GetName(idx);
            }
            string concatColumns = string.Join(""_"", array);

            switch(concatColumns)
            {
");
            
            #line 179 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      foreach(ResultSet rs in routine.ResultSets){
            
            #line default
            #line hidden
            this.Write("                case (\"");
            
            #line 180 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rs.ConcatColumns));
            
            #line default
            #line hidden
            this.Write("\"):\r\n                    return \"");
            
            #line 181 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rs.Name));
            
            #line default
            #line hidden
            this.Write("\";\r\n");
            
            #line 182 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      }
            
            #line default
            #line hidden
            this.Write(@"            }

            throw new Exception(""The multi result query could not resolve. Each query must contain at least one unique value. Edit the routine and rebuild the project needs a fresh SQL PLUS build."");
        }

        #endregion MultSet Resolver
");
            
            #line 189 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n        #region Execute Command\r\n\r\n        private void ");
            
            #line 193 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("_Execute(SqlCommand cmd, ");
            
            #line 193 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("Output output)\r\n        {\r\n");
            
            #line 195 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
if(routine.SelectType == SelectTypes.NonQuery){
            
            #line default
            #line hidden
            this.Write("            cmd.ExecuteNonQuery();\r\n");
            
            #line 197 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
}
            
            #line default
            #line hidden
            
            #line 198 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
if(routine.SelectType == SelectTypes.Json || routine.SelectType == SelectTypes.Xml){
            
            #line default
            #line hidden
            this.Write(@"            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                StringBuilder bldr = new StringBuilder();
                while (rdr.Read())
                {
                    bldr.Append(rdr.GetString(0));
                }
                rdr.Close();
                output.Result");
            
            #line 207 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.SelectType.ToString()));
            
            #line default
            #line hidden
            this.Write(" = bldr.ToString();\r\n            }\r\n");
            
            #line 209 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
}
            
            #line default
            #line hidden
            
            #line 210 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
if(routine.SelectType == SelectTypes.SingleRow || routine.SelectType == SelectTypes.MultiRow){
            
            #line default
            #line hidden
            this.Write("            using (SqlDataReader rdr = cmd.ExecuteReader())\r\n            {\r\n");
            
            #line 213 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  if(routine.SelectType == SelectTypes.SingleRow){
            
            #line default
            #line hidden
            this.Write("                if(rdr.Read())\r\n                {\r\n                    output.Res" +
                    "ultData = ");
            
            #line 216 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("_ResultData(rdr);\r\n                }\r\n");
            
            #line 218 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  }else{
            
            #line default
            #line hidden
            this.Write("                output.ResultData = new List<");
            
            #line 219 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("Result>();\r\n                while(rdr.Read())\r\n                {\r\n               " +
                    "     output.ResultData.Add(");
            
            #line 222 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("_ResultData(rdr));\r\n                }\r\n");
            
            #line 224 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
  }
            
            #line default
            #line hidden
            this.Write("                rdr.Close();\r\n            }\r\n");
            
            #line 227 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
}
            
            #line default
            #line hidden
            
            #line 228 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      if(routine.SelectType == SelectTypes.MultiSet){
            
            #line default
            #line hidden
            this.Write("            using (SqlDataReader rdr = cmd.ExecuteReader())\r\n            {\r\n     " +
                    "           do\r\n                {\r\n                    if (rdr.HasRows)\r\n        " +
                    "            {\r\n                        switch (");
            
            #line 235 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("_Resolve(rdr))\r\n                        {\r\n");
            
            #line 237 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
          foreach(ResultSet rs in routine.ResultSets){
            
            #line default
            #line hidden
            this.Write("                            case \"");
            
            #line 238 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rs.Name));
            
            #line default
            #line hidden
            this.Write("\":\r\n");
            
            #line 239 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
              if(rs.SelectType == SelectTypes.Json || rs.SelectType == SelectTypes.Xml){
            
            #line default
            #line hidden
            this.Write("\r\n                                StringBuilder ");
            
            #line 241 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rs.Name));
            
            #line default
            #line hidden
            this.Write("StringBuilder = new StringBuilder();\r\n                                while (rdr." +
                    "Read())\r\n                                {\r\n                                    " +
                    "");
            
            #line 244 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rs.Name));
            
            #line default
            #line hidden
            this.Write("StringBuilder.Append(rdr.GetString(0));\r\n                                }\r\n     " +
                    "                           ");
            
            #line 246 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(OptNotNull("output.ResultData")));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 246 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rs.Name));
            
            #line default
            #line hidden
            
            #line 246 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rs.SelectType.ToString()));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 246 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rs.Name));
            
            #line default
            #line hidden
            this.Write("StringBuilder.ToString();\r\n");
            
            #line 247 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
              }
            
            #line default
            #line hidden
            
            #line 248 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
              if(rs.SelectType == SelectTypes.SingleRow){
            
            #line default
            #line hidden
            this.Write("\r\n                                if(rdr.Read())\r\n                               " +
                    " {\r\n                                    ");
            
            #line 252 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(OptNotNull("output.ResultData")));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 252 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rs.Name));
            
            #line default
            #line hidden
            this.Write("Result = ");
            
            #line 252 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 252 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rs.Name));
            
            #line default
            #line hidden
            this.Write("(rdr);\r\n                                }\r\n");
            
            #line 254 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
              }
            
            #line default
            #line hidden
            
            #line 255 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
              if(rs.SelectType == SelectTypes.MultiRow){
            
            #line default
            #line hidden
            this.Write("\r\n                                ");
            
            #line 257 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(OptNotNull("output.ResultData")));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 257 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rs.Name));
            
            #line default
            #line hidden
            this.Write("Result = new List<");
            
            #line 257 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("Result.");
            
            #line 257 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rs.Name));
            
            #line default
            #line hidden
            this.Write(">();\r\n                                while(rdr.Read())\r\n                        " +
                    "        {\r\n                                    ");
            
            #line 260 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(OptNotNull("output.ResultData")));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 260 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rs.Name));
            
            #line default
            #line hidden
            this.Write("Result.Add(");
            
            #line 260 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 260 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rs.Name));
            
            #line default
            #line hidden
            this.Write("(rdr));\r\n                                }\r\n");
            
            #line 262 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
              }
            
            #line default
            #line hidden
            this.Write("                                break;\r\n");
            
            #line 264 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
          }
            
            #line default
            #line hidden
            this.Write("                        }\r\n                    }\r\n                } while (rdr.Ne" +
                    "xtResult());\r\n\r\n                rdr.Close();\r\n            }\r\n");
            
            #line 271 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      }
            
            #line default
            #line hidden
            
            #line 272 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      if(routine.NonInputParameters.Count != 0){
            
            #line default
            #line hidden
            this.Write("\r\n            ");
            
            #line 274 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.SetParametersName));
            
            #line default
            #line hidden
            this.Write("(cmd, output);\r\n");
            
            #line 275 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      }
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        #endregion Execute Command\r\n\r\n        #region Public Service" +
                    "\r\n\r\n        /// <summary>\r\n        /// ");
            
            #line 283 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Comment));
            
            #line default
            #line hidden
            this.Write("<br/>\r\n        /// DB Routine: ");
            
            #line 284 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Schema));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 284 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Name));
            
            #line default
            #line hidden
            this.Write("<br/>\r\n        /// Author: ");
            
            #line 285 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.Author));
            
            #line default
            #line hidden
            this.Write("<br/>\r\n        /// </summary>\r\n");
            
            #line 287 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      if(routine.InputParameters.Count != 0){
            
            #line default
            #line hidden
            this.Write("        /// <param name=\"input\">");
            
            #line 288 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.InputObjectName));
            
            #line default
            #line hidden
            this.Write(" instance.</param>\r\n");
            
            #line 289 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
}
            
            #line default
            #line hidden
            this.Write("        /// <returns>Instance of ");
            
            #line 290 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.OutputObjectName));
            
            #line default
            #line hidden
            this.Write("</returns>\r\n        public ");
            
            #line 291 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.OutputObjectName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 291 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.ServiceName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 291 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.ServiceParameters));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n");
            
            #line 293 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      if(routine.InputParameters.Count != 0){
            
            #line default
            #line hidden
            this.Write("            ValidateInput(input, nameof(");
            
            #line 294 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.ServiceName));
            
            #line default
            #line hidden
            this.Write("));\r\n");
            
            #line 295 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      }
            
            #line default
            #line hidden
            
            #line 296 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      if(routine.SelectType == SelectTypes.MultiSet){
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 297 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.OutputObjectName));
            
            #line default
            #line hidden
            this.Write(" output = new ");
            
            #line 297 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.OutputObjectName));
            
            #line default
            #line hidden
            this.Write(" { ResultData = new ");
            
            #line 297 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.ResultObjectName));
            
            #line default
            #line hidden
            this.Write("() };\r\n");
            
            #line 298 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      }else{
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 299 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.OutputObjectName));
            
            #line default
            #line hidden
            this.Write(" output = new ");
            
            #line 299 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.OutputObjectName));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 300 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      }
            
            #line default
            #line hidden
            this.Write("\t\t\tif(sqlConnection != null)\r\n            {\r\n");
            
            #line 303 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      if (routine.InputParameters.Count != 0){
            
            #line default
            #line hidden
            this.Write("                using (SqlCommand cmd = ");
            
            #line 304 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.BuildCommandName));
            
            #line default
            #line hidden
            this.Write("(sqlConnection, input))\r\n");
            
            #line 305 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      }else{
            
            #line default
            #line hidden
            this.Write("                using (SqlCommand cmd = ");
            
            #line 306 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.BuildCommandName));
            
            #line default
            #line hidden
            this.Write("(sqlConnection))\r\n");
            
            #line 307 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      }
            
            #line default
            #line hidden
            this.Write("                {\r\n                    cmd.Transaction = sqlTransaction;\r\n       " +
                    "             ");
            
            #line 310 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.ServiceName));
            
            #line default
            #line hidden
            this.Write(@"_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
");
            
            #line 323 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      if (routine.InputParameters.Count != 0){
            
            #line default
            #line hidden
            this.Write("                    using (SqlCommand cmd = ");
            
            #line 324 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.BuildCommandName));
            
            #line default
            #line hidden
            this.Write("(cnn, input))\r\n");
            
            #line 325 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      }else{
            
            #line default
            #line hidden
            this.Write("                    using (SqlCommand cmd = ");
            
            #line 326 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.BuildCommandName));
            
            #line default
            #line hidden
            this.Write("(cnn))\r\n");
            
            #line 327 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
      }
            
            #line default
            #line hidden
            this.Write("                    {\r\n                        cnn.Open();\r\n\t\t\t\t\t\t");
            
            #line 330 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routine.ServiceName));
            
            #line default
            #line hidden
            this.Write(@"_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion

    }
}

");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 348 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"

    private string OutParameterCast(Parameter p)
    {
        if (p.IsReturnValue || p.MSSQLParameterMode == "OUTPUTASRETURN")
        {
            if(routine.ReturnValueEnums.Count != 0)
            {
                return $"({routine.Name}Output.Returns)";
            }
        }

        if(p.EnumerationName != null)
        {
            return $"({p.EnumerationName})";
        }
        return $"({p.PropertyType})";
    }
    private string Format(string sourceString, int value)
    {
        return sourceString.Replace("{0}", value.ToString());
    }
    private string Format(string sourceString, string value)
    {
        return sourceString.Replace("{0}", value.ToString());
    }
    private string CommaIfNotLast(List<Column> columns, Column column)
    {
        if(columns.IndexOf(column) == columns.Count - 1)
        {
            return "";
        }
        return ",";
    }
    private string OptNotNull(string value)
    {
        if(routine.UseNullableReferenceTypes)
        {
            return value + "!";
        }
        return value;
    }

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\Alan\source\repos\sql-plus-version-four-builder\SQLPLUS.Builder\Render\T4Net\ServiceMethod.tt"

private global::SQLPLUS.Builder.TemplateModels.Routine _routineField;

/// <summary>
/// Access the routine parameter of the template.
/// </summary>
private global::SQLPLUS.Builder.TemplateModels.Routine routine
{
    get
    {
        return this._routineField;
    }
}

private global::SQLPLUS.Builder.ConfigurationModels.ProjectInformation _projectField;

/// <summary>
/// Access the project parameter of the template.
/// </summary>
private global::SQLPLUS.Builder.ConfigurationModels.ProjectInformation project
{
    get
    {
        return this._projectField;
    }
}

private global::SQLPLUS.Builder.ConfigurationModels.BuildDefinition _buildField;

/// <summary>
/// Access the build parameter of the template.
/// </summary>
private global::SQLPLUS.Builder.ConfigurationModels.BuildDefinition build
{
    get
    {
        return this._buildField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool routineValueAcquired = false;
if (this.Session.ContainsKey("routine"))
{
    this._routineField = ((global::SQLPLUS.Builder.TemplateModels.Routine)(this.Session["routine"]));
    routineValueAcquired = true;
}
if ((routineValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("routine");
    if ((data != null))
    {
        this._routineField = ((global::SQLPLUS.Builder.TemplateModels.Routine)(data));
    }
}
bool projectValueAcquired = false;
if (this.Session.ContainsKey("project"))
{
    this._projectField = ((global::SQLPLUS.Builder.ConfigurationModels.ProjectInformation)(this.Session["project"]));
    projectValueAcquired = true;
}
if ((projectValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("project");
    if ((data != null))
    {
        this._projectField = ((global::SQLPLUS.Builder.ConfigurationModels.ProjectInformation)(data));
    }
}
bool buildValueAcquired = false;
if (this.Session.ContainsKey("build"))
{
    this._buildField = ((global::SQLPLUS.Builder.ConfigurationModels.BuildDefinition)(this.Session["build"]));
    buildValueAcquired = true;
}
if ((buildValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("build");
    if ((data != null))
    {
        this._buildField = ((global::SQLPLUS.Builder.ConfigurationModels.BuildDefinition)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class ServiceMethodBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
