// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL+ .NET Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Type: [Sync].[EDispatch]
//     For more information on SQL+ .NET visit https://www.SQLPlus.net
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SQLPLUS.Build.Test.Basic.UserDefinedTypes
{
    #region usings

    using SqlPlusBase;
    using System;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

	/// <summary>
    /// Input object table value parameter EDispatch.
    /// </summary>
    public partial class EDispatch : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for EDispatch.
        /// </summary>
        public EDispatch() { }

        /// <summary>
        /// Parameterized constructor for EDispatch.
        /// </summary>
        /// <param name="Dispatch">Maps to column Dispatch.</param>
        /// <param name="CustNo">Maps to column CustNo.</param>
        /// <param name="LocNo">Maps to column LocNo.</param>
        /// <param name="Tasks">Maps to column Tasks.</param>
        /// <param name="Zone">Maps to column Zone.</param>
        /// <param name="CalledInBy">Maps to column CalledInBy.</param>
        /// <param name="Terms">Maps to column Terms.</param>
        /// <param name="PONum">Maps to column PONum.</param>
        /// <param name="RecDate">Maps to column RecDate.</param>
        /// <param name="RecTime">Maps to column RecTime.</param>
        /// <param name="RecBy">Maps to column RecBy.</param>
        /// <param name="Priority">Maps to column Priority.</param>
        /// <param name="Invoice">Maps to column Invoice.</param>
        /// <param name="Complete">Maps to column Complete.</param>
        /// <param name="TechTime">Maps to column TechTime.</param>
        /// <param name="MultiTech">Maps to column MultiTech.</param>
        /// <param name="Notes">Maps to column Notes.</param>
        /// <param name="Invoiced">Maps to column Invoiced.</param>
        /// <param name="JobNumber">Maps to column JobNumber.</param>
        /// <param name="QuoteSource">Maps to column QuoteSource.</param>
        /// <param name="Sort">Maps to column Sort.</param>
        /// <param name="Hash">Maps to column Hash.</param>
        public EDispatch(string Dispatch, string CustNo, string LocNo, string Tasks, string Zone, string CalledInBy, string Terms, string PONum, DateTime? RecDate, string RecTime, string RecBy, string Priority, string Invoice, DateTime? Complete, double TechTime, string MultiTech, string Notes, int Invoiced, string JobNumber, string QuoteSource, string Sort, int Hash)
        {
            this.Dispatch = Dispatch;
            this.CustNo = CustNo;
            this.LocNo = LocNo;
            this.Tasks = Tasks;
            this.Zone = Zone;
            this.CalledInBy = CalledInBy;
            this.Terms = Terms;
            this.PONum = PONum;
            this.RecDate = RecDate;
            this.RecTime = RecTime;
            this.RecBy = RecBy;
            this.Priority = Priority;
            this.Invoice = Invoice;
            this.Complete = Complete;
            this.TechTime = TechTime;
            this.MultiTech = MultiTech;
            this.Notes = Notes;
            this.Invoiced = Invoiced;
            this.JobNumber = JobNumber;
            this.QuoteSource = QuoteSource;
            this.Sort = Sort;
            this.Hash = Hash;
        }

        #endregion Constructors

        #region Fields

        /// <summary>
        /// Maps to table value column Dispatch.
        /// </summary>
        [Required]
        [MaxLength(15)]
        public string Dispatch { set; get; }

        /// <summary>
        /// Maps to table value column CustNo.
        /// </summary>
        [Required]
        [MaxLength(7)]
        public string CustNo { set; get; }

        /// <summary>
        /// Maps to table value column LocNo.
        /// </summary>
        [Required]
        [MaxLength(5)]
        public string LocNo { set; get; }

        /// <summary>
        /// Maps to table value column Tasks.
        /// </summary>
        [MaxLength(128)]
        public string Tasks { set; get; }

        /// <summary>
        /// Maps to table value column Zone.
        /// </summary>
        [Required]
        [MaxLength(7)]
        public string Zone { set; get; }

        /// <summary>
        /// Maps to table value column CalledInBy.
        /// </summary>
        [Required]
        [MaxLength(20)]
        public string CalledInBy { set; get; }

        /// <summary>
        /// Maps to table value column Terms.
        /// </summary>
        [Required]
        [MaxLength(5)]
        public string Terms { set; get; }

        /// <summary>
        /// Maps to table value column PONum.
        /// </summary>
        [Required]
        [MaxLength(20)]
        public string PONum { set; get; }

        /// <summary>
        /// Maps to table value column RecDate.
        /// </summary>
        public DateTime? RecDate { set; get; }

        /// <summary>
        /// Maps to table value column RecTime.
        /// </summary>
        [Required]
        [MaxLength(8)]
        public string RecTime { set; get; }

        /// <summary>
        /// Maps to table value column RecBy.
        /// </summary>
        [Required]
        [MaxLength(10)]
        public string RecBy { set; get; }

        /// <summary>
        /// Maps to table value column Priority.
        /// </summary>
        [Required]
        [MaxLength(6)]
        public string Priority { set; get; }

        /// <summary>
        /// Maps to table value column Invoice.
        /// </summary>
        [Required]
        [MaxLength(10)]
        public string Invoice { set; get; }

        /// <summary>
        /// Maps to table value column Complete.
        /// </summary>
        public DateTime? Complete { set; get; }

        /// <summary>
        /// Maps to table value column TechTime.
        /// </summary>
        [Required]
        public double TechTime { set; get; }

        /// <summary>
        /// Maps to table value column MultiTech.
        /// </summary>
        [Required]
        [MaxLength(1)]
        public string MultiTech { set; get; }

        /// <summary>
        /// Maps to table value column Notes.
        /// </summary>
        public string Notes { set; get; }

        /// <summary>
        /// Maps to table value column Invoiced.
        /// </summary>
        [Required]
        public int Invoiced { set; get; }

        /// <summary>
        /// Maps to table value column JobNumber.
        /// </summary>
        [Required]
        [MaxLength(41)]
        public string JobNumber { set; get; }

        /// <summary>
        /// Maps to table value column QuoteSource.
        /// </summary>
        [MaxLength(10)]
        public string QuoteSource { set; get; }

        /// <summary>
        /// Maps to table value column Sort.
        /// </summary>
        [Required]
        [MaxLength(6)]
        public string Sort { set; get; }

        /// <summary>
        /// Maps to table value column Hash.
        /// </summary>
        [Required]
        public int Hash { set; get; }

        #endregion Fields
    }
}