// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SQLPLUS.Builder.VSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "SQLPLUS.Builder.VSIX.aaa9ba8f-954f-46f7-8ded-96b13b290b47";
        public const string Name = "SQLPLUS.Builder.VSIX";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "alan hyneman";
        public const string Tags = "";
    }
}
