// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: AllTags
//     Last Modified On: 1/2/2023 4:56:34 PM
//     Written By: Alan Hyneman
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SQLPLUS.Builder.ConsoleBuilder.procs.Models
{
    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the AllTags service.
    /// </summary>
    public partial class AllTagsInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for AllTagsInput.
        /// </summary>
        public AllTagsInput() { }

        /// <summary>
        /// Parameterized constructor for AllTagsInput.
        /// </summary>
        /// <param name="Comment">This is a comment</param>
        /// <param name="CreditCard">Maps to parameter @CreditCard.</param>
        /// <param name="Default">Maps to parameter @Default.</param>
        /// <param name="Display">Maps to parameter @Display.</param>
        /// <param name="Email">Maps to parameter @Email.</param>
        /// <param name="EnumDayOfWeek">Maps to parameter @EnumDayOfWeek.</param>
        /// <param name="For">Testing safe for.</param>
        /// <param name="Object">Testing object.</param>
        public AllTagsInput(string Comment, string CreditCard, string Default, string Display, string Email, System.DayOfWeek? EnumDayOfWeek, string For, string Object)
        {
            this.Comment = Comment;
            this.CreditCard = CreditCard;
            this.Default = Default;
            this.Display = Display;
            this.Email = Email;
            this.EnumDayOfWeek = EnumDayOfWeek;
            this.For = For;
            this.Object = Object;
        }

        #endregion Constructors

        #region Fields

        private string _Comment;
        /// <summary>
        /// This is a comment
        /// </summary>
        public string Comment
        {
            get => _Comment;
            set => _Comment = value;
        }

        private string _CreditCard;
        /// <summary>
        /// Maps to parameter @CreditCard.
        /// </summary>
        [CreditCard]
        public string CreditCard
        {
            get => _CreditCard;
            set => _CreditCard = value;
        }

        private string _Default = "";
        /// <summary>
        /// Maps to parameter @Default.
        /// </summary>
        public string Default
        {
            get => _Default;
            set => _Default = value;
        }

        private string _Display;
        /// <summary>
        /// Maps to parameter @Display.
        /// </summary>
        [Display(Name = "Display Name", Description = "DisplayDescription")]
        public string Display
        {
            get => _Display;
            set => _Display = value;
        }

        private string _Email;
        /// <summary>
        /// Maps to parameter @Email.
        /// </summary>
        [EmailAddress]
        public string Email
        {
            get => _Email;
            set => _Email = value;
        }

        private System.DayOfWeek? _EnumDayOfWeek;
        /// <summary>
        /// Maps to parameter @EnumDayOfWeek.
        /// </summary>
        public System.DayOfWeek? EnumDayOfWeek
        {
            get => _EnumDayOfWeek;
            set => _EnumDayOfWeek = value;
        }

        private string _For;
        /// <summary>
        /// Testing safe for.
        /// </summary>
        public string For
        {
            get => _For;
            set => _For = value;
        }

        private string _Object;
        /// <summary>
        /// Testing object.
        /// </summary>
        public string Object
        {
            get => _Object;
            set => _Object = value;
        }

        #endregion

    }
}