// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using SQLPLUS.Builder.DataServices.MSSQL.Models;

namespace SQLPLUS.Builder.DataServices.MSSQL
{
    public partial class Service
    {

        /// <summary>
        /// Builds the command object for ResultColumnsForText method.
        /// </summary>
        /// <param name="cnn">The connection that will execute the procedure.</param>
        /// <param name="input">ResultColumnsForTextInput instance for loading parameter values.</param>
        /// <returns>SqlCommand ready for execution.</returns>
        private SqlCommand GetResultColumnsForTextCommand(SqlConnection cnn, IResultColumnsForTextInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.Text,
                CommandText = @"
SELECT
[column_ordinal] - 1 AS [Index],
CAST([name] AS VARCHAR(128)) AS [Name],
[is_nullable] AS [IsNullable],
CASE
WHEN Charindex('(', system_type_name) = 0 THEN system_type_name
ELSE Left(system_type_name, Charindex('(', system_type_name) - 1)
END [SQLType],
CASE
WHEN TYPE_NAME(system_type_id) IN ('char','varchar','nchar','nvarchar','binary','varbinary') THEN CONVERT(int,[max_length])
ELSE NULL
END [CharacterMaxLength],
CASE
WHEN TYPE_NAME(system_type_id) IN ('numeric', 'decimal') THEN [precision]
ELSE NULL
END [NumericPrecision],
CASE
WHEN TYPE_NAME(system_type_id) IN ('time', 'datetimeoffset', 'datetime2') THEN [scale]
ELSE NULL
END [DateTimePrecision],
CASE
WHEN TYPE_NAME(system_type_id) IN ('numeric', 'decimal') THEN [scale]
ELSE NULL
END [NumericScale]
FROM
sys.dm_exec_describe_first_result_set(@SQLText, null, 1)
WHERE
IS_HIDDEN = 0
IF @@ROWCOUNT = 0
BEGIN
SET @ReturnValue=0;
END;
ELSE
BEGIN
SET @ReturnValue = 1;
END;",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@SQLText",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.VarChar,
                Size = 8000,
				Value = input.SQLText
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.Output,
                SqlDbType = SqlDbType.Int,
                Value = DBNull.Value
            });

            return result;
        }
        private void SetResultColumnsForTextCommandOutputs(SqlCommand cmd, ResultColumnsForTextOutput output)
        {
            if(cmd.Parameters[1].Value != DBNull.Value)
            {
                output.ReturnValue = (ResultColumnsForTextOutput.Returns)cmd.Parameters[1].Value;
            }
        }

        private ResultColumnsForTextResult GetResultColumnsForTextResultFromReader(SqlDataReader rdr)
        {
            ResultColumnsForTextResult result = new ResultColumnsForTextResult();

            if(!rdr.IsDBNull(0))
            {
                result.Index = rdr.GetInt32(0);
            }

            if(!rdr.IsDBNull(1))
            {
                result.Name = rdr.GetString(1);
            }

            if(!rdr.IsDBNull(2))
            {
                result.IsNullable = rdr.GetBoolean(2);
            }

            if(!rdr.IsDBNull(3))
            {
                result.SQLType = rdr.GetString(3);
            }

            if(!rdr.IsDBNull(4))
            {
                result.CharacterMaxLength = rdr.GetInt32(4);
            }

            if(!rdr.IsDBNull(5))
            {
                result.NumericPrecision = rdr.GetByte(5);
            }

            if(!rdr.IsDBNull(6))
            {
                result.DateTimePrecision = rdr.GetByte(6);
            }

            if(!rdr.IsDBNull(7))
            {
                result.NumericScale = rdr.GetByte(7);
            }

            return result;
        }


        private void ResultColumnsForTextCommand(SqlCommand cmd, ResultColumnsForTextOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                output.ResultData = new List<ResultColumnsForTextResult>();
                while(rdr.Read())
                {
                    output.ResultData.Add(GetResultColumnsForTextResultFromReader(rdr));
                }
                rdr.Close();
            }
            SetResultColumnsForTextCommandOutputs(cmd, output);
        }

        /// <summary>
        /// Gets the result column meta data for SQL Text. Note it will not work for table functions, use columns for table instead.
        /// SQL+ Routine: .ResultColumnsForText - Authored by Alan Hyneman
        /// </summary>
        public ResultColumnsForTextOutput ResultColumnsForText(IResultColumnsForTextInput input, bool bypassValidation = false)
        {
            if(!bypassValidation)
            {
                if (!input.IsValid())
                {
		            throw new ArgumentException("ResultColumnsForTextInput fails validation - use the ResultColumnsForTextInput.IsValid() method prior to passing the input argument to the ResultColumnsForText method.", "input");
                }
            }
            ResultColumnsForTextOutput output = new ResultColumnsForTextOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetResultColumnsForTextCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    ResultColumnsForTextCommand(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if(idx > 0)
                {
                    System.Threading.Thread.Sleep(retryOptions.RetryIntervals[idx-1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetResultColumnsForTextCommand(cnn, input))
                    {
                        cnn.Open();
						ResultColumnsForTextCommand(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    bool throwException = true;

                    if(retryOptions.TransientErrorNumbers.Contains(sqlException.Number))
                    {
                        throwException = (idx == retryOptions.RetryIntervals.Count);

                        if (retryOptions.Logger != null)
                        {
                            retryOptions.Logger.Log(sqlException);
                        }
                    }
                    if(throwException)
                    {
                        throw;
                    }
                }
            }
            return output;
        }
    }
}