// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerInfoById
//     Last Modified On: 2/18/2023 6:22:05 PM
//     Written By: Alan
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SQLPlus.AzureFunctions.Default.Models
{
    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the CustomerInfoById service.
    /// </summary>
    public partial class CustomerInfoByIdInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for CustomerInfoByIdInput.
        /// </summary>
        public CustomerInfoByIdInput() { }

        /// <summary>
        /// Parameterized constructor for CustomerInfoByIdInput.
        /// </summary>
        /// <param name="CustomerId">Maps to parameter @CustomerId.</param>
        public CustomerInfoByIdInput(int? CustomerId)
        {
            this.CustomerId = CustomerId;
        }

        #endregion Constructors

        #region Fields

        private int? _CustomerId;
        /// <summary>
        /// Maps to parameter @CustomerId.
        /// </summary>
        [Required]
        public int? CustomerId
        {
            get => _CustomerId;
            set => _CustomerId = value;
        }

        #endregion

    }
}