// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: ErrorLogInsert
//     Last Modified On: 2/12/2023 11:50:43 AM
//     Written By: alan
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SQLPlus.AzureFunctions.Default.Models
{
    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the ErrorLogInsert service.
    /// </summary>
    public partial class ErrorLogInsertInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for ErrorLogInsertInput.
        /// </summary>
        public ErrorLogInsertInput() { }

        /// <summary>
        /// Parameterized constructor for ErrorLogInsertInput.
        /// </summary>
        /// <param name="CustomerId">CustomerId</param>
        /// <param name="ErrorMessage">ErrorMessage</param>
        public ErrorLogInsertInput(int? CustomerId, string ErrorMessage)
        {
            this.CustomerId = CustomerId;
            this.ErrorMessage = ErrorMessage;
        }

        #endregion Constructors

        #region Fields

        private int? _CustomerId;
        /// <summary>
        /// CustomerId
        /// </summary>
        public int? CustomerId
        {
            get => _CustomerId;
            set => _CustomerId = value;
        }

        private string _ErrorMessage;
        /// <summary>
        /// ErrorMessage
        /// </summary>
        public string ErrorMessage
        {
            get => _ErrorMessage;
            set => _ErrorMessage = value;
        }

        #endregion

    }
}