// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerInfoById
//     Last Modified On: 2/18/2023 6:22:05 PM
//     Written By: Alan
//     Visit https://www.SQLPLUS.net for more information about the SQL PLUS build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace SQLPlus.AzureFunctions.Default
{
    #region Using Statments

    using SQLPlus.AzureFunctions.Default.Models;
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Threading;

    #endregion Using Statements

    /// <summary>
    /// This file contains the source code for the CustomerInfoById routine.
    /// </summary>
    public partial class Service
    {
        #region Build SqlCommand

        private SqlCommand CustomerInfoById_BuildCommand(SqlConnection cnn, CustomerInfoByIdInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[CustomerInfoById]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@CustomerId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = input.CustomerId
            });

            return result;
        }

        #endregion Build SqlCommand

        #region Read Output Parameters And Return Value

        private void CustomerInfoById_SetParameters(SqlCommand cmd, CustomerInfoByIdOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (CustomerInfoByIdOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        #endregion Read Output Parameters And Return Value

        #region Reader To Result Objects
        
        private CustomerInfoByIdResult CustomerInfoById_ResultData(SqlDataReader rdr)
        {
            return new CustomerInfoByIdResult(
            rdr.GetInt32(0),
            rdr.GetBoolean(1),
            rdr.GetDateTime(2),
            rdr.GetDateTime(3),
            rdr.GetString(4),
            rdr.GetString(5),
            rdr.GetString(6),
            rdr.GetString(7),
            rdr.GetString(8),
            rdr.IsDBNull(9) ? default : rdr.GetString(9),
            rdr.IsDBNull(10) ? default : rdr.GetString(10)
            );
        }
    
        #endregion Reader To Result Objects

        #region Execute Command

        private void CustomerInfoById_Execute(SqlCommand cmd, CustomerInfoByIdOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                if(rdr.Read())
                {
                    output.ResultData = CustomerInfoById_ResultData(rdr);
                }
                rdr.Close();
            }

            CustomerInfoById_SetParameters(cmd, output);
        }

        #endregion Execute Command

        #region Public Service

        /// <summary>
        /// Customer information for the given customer Id.<br/>
        /// DB Routine: dbo.CustomerInfoById<br/>
        /// Author: Alan<br/>
        /// </summary>
        /// <param name="input">CustomerInfoByIdInput instance.</param>
        /// <returns>Instance of CustomerInfoByIdOutput</returns>
        public CustomerInfoByIdOutput CustomerInfoById(CustomerInfoByIdInput input)
        {
            ValidateInput(input, nameof(CustomerInfoById));
            CustomerInfoByIdOutput output = new CustomerInfoByIdOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = CustomerInfoById_BuildCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    CustomerInfoById_Execute(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = CustomerInfoById_BuildCommand(cnn, input))
                    {
                        cnn.Open();
						CustomerInfoById_Execute(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }

        #endregion

    }
}

