// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;
namespace SQLPLUS.Builder.DataServices.MSSQL.Models
{
    /// <summary>
    /// Result object for ResultColumnsForTable routine.
    /// </summary>
    public partial class ResultColumnsForTableResult
	{
        public int? Index { set; get; }
        public string Name { set; get; }
        public bool? IsNullable { set; get; }
        public string SQLType { set; get; }
        public int? CharacterMaxLength { set; get; }
        public int? NumericPrecision { set; get; }
        public int? DateTimePrecision { set; get; }
        public int? NumericScale { set; get; }
    }
}