// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SQLPLUS.Builder.DataServices.MSSQL.Models
{
    /// <summary>
    /// Interface for ResultColumnsForTableInput object.
    /// </summary>
    public interface IResultColumnsForTableInput : IValidInput
    {
        string Schema { set; get; }
        string Function { set; get; }
    }

    /// <summary>
    /// Input object for ResultColumnsForTable method.
    /// </summary>
    public class ResultColumnsForTableInput : ValidInput, IResultColumnsForTableInput
    {
        /// <summary>
        /// Set this value for all calls
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        public string Schema { set; get; }

        [Required(AllowEmptyStrings = false)]
        public string Function { set; get; }

    }
} 