// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;
namespace SQLPLUS.Builder.DataServices.MSSQL.Models
{
    /// <summary>
    /// Result object for RoutineParameters routine.
    /// </summary>
    public partial class RoutineParametersResult
	{
        public string Name { set; get; }
        public string Mode { set; get; }
        public string SQLType { set; get; }
        public int? CharacterMaxLength { set; get; }
        public byte? NumericPrecision { set; get; }
        public int? NumericScale { set; get; }
        public short? DateTimePrecision { set; get; }
        public string UserDefinedTypeSchema { set; get; }
        public string UserDefinedTypeName { set; get; }
        public int OrdinalPosition { set; get; }
    }
}